spring.application.name=expense-tracker

# Change this to "prod" when you want to use MySQL
spring.profiles.active=prod

# JWT settings
jwt.secret=${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3QgdG9rZW4gZ2VuZXJhdGlvbiBpbiBleHBlbnNlIHRyYWNrZXI=}
jwt.expiration=${JWT_EXPIRATION:86400000}

# JPA common settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
